---
oc_bianry: /home/kontinuity/oc/oc
git_source_repository: https://github.com/redhat-kontinuity/catapult
git_source_ref: master
destination_repository: redhatdevelopers
destination_image: catapult
destination_tag: latest