- hosts: localhost
  connection: local
  tasks:
      - name: Enable centos-release-scl repo
        yum: name=centos-release-scl state=latest

      - name: Setup libvirt + Vagrant
        tags: libvirt
        yum: name={{item}} state=latest
        with_items:
            - sclo-vagrant1
            - qemu-kvm

      - name: Miscellaneous packages
        yum: name={{item}} state=latest
        with_items:
            - git
            - wget

      - name: Start and enable libvirtd daemon
        service: name=libvirtd state=started enabled=yes

      - name: Clone the ADB repo and move further only if it succeeds (GH might be down)
        git: repo=https://github.com/projectatomic/adb-atomic-developer-bundle dest=/root/adb

